<?php
    /** @var \JaroslawZielinski\FeaturePoll\Block\Adminhtml\Analytics\Button $block */
    /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
    $id = $block->getHtmlId();
    $classes = $block->getHtmlClass();
    $label = $block->getLabel();
    $url = $block->getUrl($block->getRedirectUrl());
?>
<button type="button" id="<?= $id; ?>" class="<?= $classes; ?>"><?= $label; ?></button>
<?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
    'onclick',
    "window.open('{$url}', '_parent', 'menubar=yes')",
    'button#' . $id
); ?>
